// Auto-generated by deploy.cjs
export const CONTRACT_ADDRESS = "0x9A672A7725848A1A2CdF36F811533174aDA6C0f7";
export const NETWORK = "sepolia";
export const CHAIN_ID = 11155111;
export const DEPLOYER = "0x6CF962667A31eFc9aD33Bf12D7d6394dd34d4E58";

export const ABI = [
  {
    "anonymous": false,
    "inputs": [
      { "indexed": true,  "internalType": "uint256", "name": "id",        "type": "uint256" },
      { "indexed": false, "internalType": "string",  "name": "cid",       "type": "string"  },
      { "indexed": false, "internalType": "string",  "name": "fileName",  "type": "string"  },
      { "indexed": true,  "internalType": "address", "name": "uploader",  "type": "address" },
      { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }
    ],
    "name": "FileStored",
    "type": "event"
  },
  {
    "inputs": [
      { "internalType": "uint256", "name": "id",   "type": "uint256" }
    ],
    "name": "getFile",
    "outputs": [
      {
        "components": [
          { "internalType": "uint256", "name": "id",        "type": "uint256" },
          { "internalType": "string",  "name": "cid",       "type": "string"  },
          { "internalType": "string",  "name": "fileName",  "type": "string"  },
          { "internalType": "uint256", "name": "fileSize",  "type": "uint256" },
          { "internalType": "bool",    "name": "encrypted", "type": "bool"    },
          { "internalType": "address", "name": "uploader",  "type": "address" },
          { "internalType": "uint256", "name": "timestamp", "type": "uint256" }
        ],
        "internalType": "struct IPFSStorage.FileRecord",
        "name": "", "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "uint256", "name": "from",  "type": "uint256" },
      { "internalType": "uint256", "name": "count", "type": "uint256" }
    ],
    "name": "getFiles",
    "outputs": [
      {
        "components": [
          { "internalType": "uint256", "name": "id",        "type": "uint256" },
          { "internalType": "string",  "name": "cid",       "type": "string"  },
          { "internalType": "string",  "name": "fileName",  "type": "string"  },
          { "internalType": "uint256", "name": "fileSize",  "type": "uint256" },
          { "internalType": "bool",    "name": "encrypted", "type": "bool"    },
          { "internalType": "address", "name": "uploader",  "type": "address" },
          { "internalType": "uint256", "name": "timestamp", "type": "uint256" }
        ],
        "internalType": "struct IPFSStorage.FileRecord[]",
        "name": "", "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{ "internalType": "address", "name": "user", "type": "address" }],
    "name": "getUserFiles",
    "outputs": [
      {
        "components": [
          { "internalType": "uint256", "name": "id",        "type": "uint256" },
          { "internalType": "string",  "name": "cid",       "type": "string"  },
          { "internalType": "string",  "name": "fileName",  "type": "string"  },
          { "internalType": "uint256", "name": "fileSize",  "type": "uint256" },
          { "internalType": "bool",    "name": "encrypted", "type": "bool"    },
          { "internalType": "address", "name": "uploader",  "type": "address" },
          { "internalType": "uint256", "name": "timestamp", "type": "uint256" }
        ],
        "internalType": "struct IPFSStorage.FileRecord[]",
        "name": "", "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "string",  "name": "cid",       "type": "string"  },
      { "internalType": "string",  "name": "fileName",  "type": "string"  },
      { "internalType": "uint256", "name": "fileSize",  "type": "uint256" },
      { "internalType": "bool",    "name": "encrypted", "type": "bool"    }
    ],
    "name": "storeFile",
    "outputs": [{ "internalType": "uint256", "name": "id", "type": "uint256" }],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "totalFiles",
    "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
    "stateMutability": "view",
    "type": "function"
  }
];
